import os

scene_path = r'D:\Unity\Projects\royalRun\Assets\Scenes\MainLevel.unity'

yaml_block = (
    "--- !u!1 &2300000001\n"
    "GameObject:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  serializedVersion: 6\n"
    "  m_Component:\n"
    "  - component: {fileID: 2300000002}\n"
    "  - component: {fileID: 2300000005}\n"
    "  - component: {fileID: 2300000004}\n"
    "  - component: {fileID: 2300000003}\n"
    "  m_Layer: 5\n"
    "  m_Name: Dev Tools Button\n"
    "  m_TagString: Untagged\n"
    "  m_Icon: {fileID: 0}\n"
    "  m_NavMeshLayer: 0\n"
    "  m_StaticEditorFlags: 0\n"
    "  m_IsActive: 1\n"
    "--- !u!224 &2300000002\n"
    "RectTransform:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000001}\n"
    "  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}\n"
    "  m_LocalPosition: {x: 0, y: 0, z: 0}\n"
    "  m_LocalScale: {x: 1, y: 1, z: 1}\n"
    "  m_ConstrainProportionsScale: 0\n"
    "  m_Children:\n"
    "  - {fileID: 2300000007}\n"
    "  m_Father: {fileID: 2048869121}\n"
    "  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}\n"
    "  m_AnchorMin: {x: 0, y: 1}\n"
    "  m_AnchorMax: {x: 0, y: 1}\n"
    "  m_AnchoredPosition: {x: 50, y: -172.5}\n"
    "  m_SizeDelta: {x: 160, y: 30}\n"
    "  m_Pivot: {x: 0.5, y: 0.5}\n"
    "--- !u!114 &2300000003\n"
    "MonoBehaviour:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000001}\n"
    "  m_Enabled: 1\n"
    "  m_EditorHideFlags: 0\n"
    "  m_Script: {fileID: 11500000, guid: 4e29b1a8efbd4b44bb3f3716e73f07ff, type: 3}\n"
    "  m_Name:\n"
    "  m_EditorClassIdentifier: UnityEngine.UI::UnityEngine.UI.Button\n"
    "  m_Navigation:\n"
    "    m_Mode: 3\n"
    "    m_WrapAround: 0\n"
    "    m_SelectOnUp: {fileID: 0}\n"
    "    m_SelectOnDown: {fileID: 0}\n"
    "    m_SelectOnLeft: {fileID: 0}\n"
    "    m_SelectOnRight: {fileID: 0}\n"
    "  m_Transition: 1\n"
    "  m_Colors:\n"
    "    m_NormalColor: {r: 1, g: 1, b: 1, a: 1}\n"
    "    m_HighlightedColor: {r: 0.9607843, g: 0.9607843, b: 0.9607843, a: 1}\n"
    "    m_PressedColor: {r: 0.78431374, g: 0.78431374, b: 0.78431374, a: 1}\n"
    "    m_SelectedColor: {r: 0.9607843, g: 0.9607843, b: 0.9607843, a: 1}\n"
    "    m_DisabledColor: {r: 0.78431374, g: 0.78431374, b: 0.78431374, a: 0.5019608}\n"
    "    m_ColorMultiplier: 1\n"
    "    m_FadeDuration: 0.1\n"
    "  m_SpriteState:\n"
    "    m_HighlightedSprite: {fileID: 0}\n"
    "    m_PressedSprite: {fileID: 0}\n"
    "    m_SelectedSprite: {fileID: 0}\n"
    "    m_DisabledSprite: {fileID: 0}\n"
    "  m_AnimationTriggers:\n"
    "    m_NormalTrigger: Normal\n"
    "    m_HighlightedTrigger: Highlighted\n"
    "    m_PressedTrigger: Pressed\n"
    "    m_SelectedTrigger: Selected\n"
    "    m_DisabledTrigger: Disabled\n"
    "  m_Interactable: 1\n"
    "  m_TargetGraphic: {fileID: 2300000004}\n"
    "  m_OnClick:\n"
    "    m_PersistentCalls:\n"
    "      m_Calls:\n"
    "      - m_Target: {fileID: 490795471}\n"
    "        m_TargetAssemblyTypeName: SettingsUI, Assembly-CSharp\n"
    "        m_MethodName: ShowDevTools\n"
    "        m_Mode: 1\n"
    "        m_Arguments:\n"
    "          m_ObjectArgument: {fileID: 0}\n"
    "          m_ObjectArgumentAssemblyTypeName: UnityEngine.Object, UnityEngine\n"
    "          m_IntArgument: 0\n"
    "          m_FloatArgument: 0\n"
    "          m_StringArgument:\n"
    "          m_BoolArgument: 0\n"
    "        m_CallState: 2\n"
    "--- !u!114 &2300000004\n"
    "MonoBehaviour:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000001}\n"
    "  m_Enabled: 1\n"
    "  m_EditorHideFlags: 0\n"
    "  m_Script: {fileID: 11500000, guid: fe87c0e1cc204ed48ad3b37840f39efc, type: 3}\n"
    "  m_Name:\n"
    "  m_EditorClassIdentifier: UnityEngine.UI::UnityEngine.UI.Image\n"
    "  m_Material: {fileID: 0}\n"
    "  m_Color: {r: 1, g: 1, b: 1, a: 1}\n"
    "  m_RaycastTarget: 1\n"
    "  m_RaycastPadding: {x: 0, y: 0, z: 0, w: 0}\n"
    "  m_Maskable: 1\n"
    "  m_OnCullStateChanged:\n"
    "    m_PersistentCalls:\n"
    "      m_Calls: []\n"
    "  m_Sprite: {fileID: 10905, guid: 0000000000000000f000000000000000, type: 0}\n"
    "  m_Type: 1\n"
    "  m_PreserveAspect: 0\n"
    "  m_FillCenter: 1\n"
    "  m_FillMethod: 4\n"
    "  m_FillAmount: 1\n"
    "  m_FillClockwise: 1\n"
    "  m_FillOrigin: 0\n"
    "  m_UseSpriteMesh: 0\n"
    "  m_PixelsPerUnitMultiplier: 1\n"
    "--- !u!222 &2300000005\n"
    "CanvasRenderer:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000001}\n"
    "  m_CullTransparentMesh: 1\n"
    "--- !u!1 &2300000006\n"
    "GameObject:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  serializedVersion: 6\n"
    "  m_Component:\n"
    "  - component: {fileID: 2300000007}\n"
    "  - component: {fileID: 2300000009}\n"
    "  - component: {fileID: 2300000008}\n"
    "  m_Layer: 5\n"
    "  m_Name: Text (TMP)\n"
    "  m_TagString: Untagged\n"
    "  m_Icon: {fileID: 0}\n"
    "  m_NavMeshLayer: 0\n"
    "  m_StaticEditorFlags: 0\n"
    "  m_IsActive: 1\n"
    "--- !u!224 &2300000007\n"
    "RectTransform:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000006}\n"
    "  m_LocalRotation: {x: -0, y: -0, z: -0, w: 1}\n"
    "  m_LocalPosition: {x: 0, y: 0, z: 0}\n"
    "  m_LocalScale: {x: 1, y: 1, z: 1}\n"
    "  m_ConstrainProportionsScale: 0\n"
    "  m_Children: []\n"
    "  m_Father: {fileID: 2300000002}\n"
    "  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}\n"
    "  m_AnchorMin: {x: 0, y: 0}\n"
    "  m_AnchorMax: {x: 1, y: 1}\n"
    "  m_AnchoredPosition: {x: 0, y: 0}\n"
    "  m_SizeDelta: {x: 0, y: 0}\n"
    "  m_Pivot: {x: 0.5, y: 0.5}\n"
    "--- !u!114 &2300000008\n"
    "MonoBehaviour:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000006}\n"
    "  m_Enabled: 1\n"
    "  m_EditorHideFlags: 0\n"
    "  m_Script: {fileID: 11500000, guid: f4688fdb7df04437aeb418b961361dc5, type: 3}\n"
    "  m_Name:\n"
    "  m_EditorClassIdentifier: Unity.TextMeshPro::TMPro.TextMeshProUGUI\n"
    "  m_Material: {fileID: 0}\n"
    "  m_Color: {r: 1, g: 1, b: 1, a: 1}\n"
    "  m_RaycastTarget: 1\n"
    "  m_RaycastPadding: {x: 0, y: 0, z: 0, w: 0}\n"
    "  m_Maskable: 1\n"
    "  m_OnCullStateChanged:\n"
    "    m_PersistentCalls:\n"
    "      m_Calls: []\n"
    "  m_text: Dev Tools\n"
    "  m_isRightToLeft: 0\n"
    "  m_fontAsset: {fileID: 11400000, guid: 8f586378b4e144a9851e7b34d9b748ee, type: 2}\n"
    "  m_sharedMaterial: {fileID: 2180264, guid: 8f586378b4e144a9851e7b34d9b748ee, type: 2}\n"
    "  m_fontSharedMaterials: []\n"
    "  m_fontMaterial: {fileID: 0}\n"
    "  m_fontMaterials: []\n"
    "  m_fontColor32:\n"
    "    serializedVersion: 2\n"
    "    rgba: 4281479730\n"
    "  m_fontColor: {r: 0.19607843, g: 0.19607843, b: 0.19607843, a: 1}\n"
    "  m_enableVertexGradient: 0\n"
    "  m_colorMode: 3\n"
    "  m_fontColorGradient:\n"
    "    topLeft: {r: 1, g: 1, b: 1, a: 1}\n"
    "    topRight: {r: 1, g: 1, b: 1, a: 1}\n"
    "    bottomLeft: {r: 1, g: 1, b: 1, a: 1}\n"
    "    bottomRight: {r: 1, g: 1, b: 1, a: 1}\n"
    "  m_fontColorGradientPreset: {fileID: 0}\n"
    "  m_spriteAsset: {fileID: 0}\n"
    "  m_tintAllSprites: 0\n"
    "  m_StyleSheet: {fileID: 0}\n"
    "  m_TextStyleHashCode: -1183493901\n"
    "  m_overrideHtmlColors: 0\n"
    "  m_faceColor:\n"
    "    serializedVersion: 2\n"
    "    rgba: 4294967295\n"
    "  m_fontSize: 24\n"
    "  m_fontSizeBase: 24\n"
    "  m_fontWeight: 400\n"
    "  m_enableAutoSizing: 0\n"
    "  m_fontSizeMin: 18\n"
    "  m_fontSizeMax: 72\n"
    "  m_fontStyle: 0\n"
    "  m_HorizontalAlignment: 2\n"
    "  m_VerticalAlignment: 512\n"
    "  m_textAlignment: 65535\n"
    "  m_characterSpacing: 0\n"
    "  m_characterHorizontalScale: 1\n"
    "  m_wordSpacing: 0\n"
    "  m_lineSpacing: 0\n"
    "  m_lineSpacingMax: 0\n"
    "  m_paragraphSpacing: 0\n"
    "  m_charWidthMaxAdj: 0\n"
    "  m_TextWrappingMode: 1\n"
    "  m_wordWrappingRatios: 0.4\n"
    "  m_overflowMode: 0\n"
    "  m_linkedTextComponent: {fileID: 0}\n"
    "  parentLinkedComponent: {fileID: 0}\n"
    "  m_enableKerning: 0\n"
    "  m_ActiveFontFeatures: 6e72656b\n"
    "  m_enableExtraPadding: 0\n"
    "  checkPaddingRequired: 0\n"
    "  m_isRichText: 1\n"
    "  m_EmojiFallbackSupport: 1\n"
    "  m_parseCtrlCharacters: 1\n"
    "  m_isOrthographic: 1\n"
    "  m_isCullingEnabled: 0\n"
    "  m_horizontalMapping: 0\n"
    "  m_verticalMapping: 0\n"
    "  m_uvLineOffset: 0\n"
    "  m_geometrySortingOrder: 0\n"
    "  m_IsTextObjectScaleStatic: 0\n"
    "  m_VertexBufferAutoSizeReduction: 0\n"
    "  m_useMaxVisibleDescender: 1\n"
    "  m_pageToDisplay: 1\n"
    "  m_margin: {x: 0, y: 0, z: 0, w: 0}\n"
    "  m_isUsingLegacyAnimationComponent: 0\n"
    "  m_isVolumetricText: 0\n"
    "  m_hasFontAssetChanged: 0\n"
    "  m_baseMaterial: {fileID: 0}\n"
    "  m_maskOffset: {x: 0, y: 0, z: 0, w: 0}\n"
    "--- !u!222 &2300000009\n"
    "CanvasRenderer:\n"
    "  m_ObjectHideFlags: 0\n"
    "  m_CorrespondingSourceObject: {fileID: 0}\n"
    "  m_PrefabInstance: {fileID: 0}\n"
    "  m_PrefabAsset: {fileID: 0}\n"
    "  m_GameObject: {fileID: 2300000006}\n"
    "  m_CullTransparentMesh: 1\n"
)

with open(scene_path, 'a', encoding='utf-8') as f:
    f.write(yaml_block)

print('Done')
